apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bfydh8y5m-nodejs
  janus-idp.io/tekton: bfydh8y5m-nodejs
  backstage.io/kubernetes-id: bfydh8y5m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bfydh8y5m-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
